### ISSUE TITLE
make errors of your version of KMC

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [tbenavi1/smooth_het#1]
Hi Timothy,
I am sorry if this may not be a good place to initiate issues, but I didn't find a place where it is appropriate.
I am trying to use the smudge_pairs.cpp program of your version of the KMC program.
However, I had an issue while doing make.
The error message is as follows:
g++ -lm -static -O3 -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -std=c++11 -o bin/kmc kmer_counter/kmer_counter.o kmer_counter/mmer.o kmer_counter/mem_disk_file.o kmer_counter/rev_byte.o kmer_counter/bkb_writer.o kmer_counter/cpu_info.o kmer_counter/bkb_reader.o kmer_counter/fastq_reader.o kmer_counter/timer.o kmer_counter/develop.o kmer_counter/kb_completer.o kmer_counter/kb_storer.o kmer_counter/kmer.o kmer_counter/splitter.o kmer_counter/kb_collector.o kmer_counter/raduls_sse2.o kmer_counter/raduls_sse41.o kmer_counter/raduls_avx2.o kmer_counter/raduls_avx.o kmer_counter/libs/libz.a kmer_counter/libs/libbz2.a
/public/home/yangzhzh/.linuxbrew/bin/ld: cannot find -lpthread
/public/home/yangzhzh/.linuxbrew/bin/ld: cannot find -lm
/public/home/yangzhzh/.linuxbrew/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make: *** [kmc] Error 1

thanks much, and looking forward to your reply.
best,
Zhenzhen

**Comment by tbenavi1** [comment]
Hello,
Thanks for your comment. What c++ compiler are you using? Some parts of KMC use C++14 features, so you need a compatible C++ compiler, e.g., gcc 4.9+ or clang 3.4+. Thanks.

**Comment by zhenzhenyang-psu** [comment]
Hi my gcc version is 5.5.0, here is the output of gcc -v:
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/public/software/compiler/gnu/5.5.0/libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ./configure --prefix=/public/software/compiler/gnu/5.5.0/ --disable-multilib
Thread model: posix
gcc version 5.5.0 (GCC) 

thanks,
Zhenzhen

**Comment by tbenavi1** [comment]
Hello,

I am not sure what the issue is. What is your g++ version ("g++ -v")? Are you able to compile the original version of KMC? From the KMC issues, I found https://github.com/refresh-bio/KMC/issues/79 which may help.

**Comment by zhenzhenyang-psu** [comment]
HI Timothy,
thanks so much for your help. It worked with the modified makefile.
best,
Zhenzhen
